<a href="https://colab.research.google.com/github/sanchit-Thakur/ML-exp-3.2-/blob/main/MLexp_3_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import sklearn as sklearn
df = pd.read_csv("/content/student_performance_dataset.csv")
print(data)

     student_id  gender  study_time_hours  attendance_percent  sleep_hours  \
0             1    Male               4.0                98.0          6.5
1             2  Female               6.3               100.0          5.7
2             3    Male               4.9                85.3          7.9
3             4    Male               2.6                77.5          8.0
4             5    Male               2.2                89.6          4.6
..          ...     ...               ...                 ...          ...
995         996    Male               2.8                75.4          8.2
996         997    Male               6.7                88.4          7.1
997         998  Female               2.6                84.5          8.0
998         999  Female               4.6                85.3          8.1
999        1000    Male               3.9                77.4          6.1

    parental_education internet_access extracurricular_activities  \
0            Bachelors             Yes                        Yes
1          High School             Yes                        Yes
2            Bachelors             Yes                         No
3                  NaN             Yes                        Yes
4            Bachelors             Yes                         No
..                 ...             ...                        ...
995            Masters             Yes                        Yes
996                NaN              No                        Yes
997        High School             Yes                        Yes
998        High School              No                         No
999            Masters             Yes                         No

    part_time_job  previous_grade  final_exam_score final_grade
0              No            76.9             100.0           A
1             Yes            75.5             100.0           A
2             Yes            88.5              97.3           A
3              No            85.1              83.8           B
4             Yes            61.8              68.3           D
..            ...             ...               ...         ...
995            No            60.5              70.7           C
996            No            82.2              99.5           A
997           Yes            65.2              79.2           C
998           Yes            52.2              82.2           B
999            No            45.4              70.4           C

[1000 rows x 12 columns]

In [ ]:
print(df)

     student_id  gender  study_time_hours  attendance_percent  sleep_hours  \
0             1    Male               4.0                98.0          6.5
1             2  Female               6.3               100.0          5.7
2             3    Male               4.9                85.3          7.9
3             4    Male               2.6                77.5          8.0
4             5    Male               2.2                89.6          4.6
..          ...     ...               ...                 ...          ...
995         996    Male               2.8                75.4          8.2
996         997    Male               6.7                88.4          7.1
997         998  Female               2.6                84.5          8.0
998         999  Female               4.6                85.3          8.1
999        1000    Male               3.9                77.4          6.1

    parental_education internet_access extracurricular_activities  \
0            Bachelors             Yes                        Yes
1          High School             Yes                        Yes
2            Bachelors             Yes                         No
3                  NaN             Yes                        Yes
4            Bachelors             Yes                         No
..                 ...             ...                        ...
995            Masters             Yes                        Yes
996                NaN              No                        Yes
997        High School             Yes                        Yes
998        High School              No                         No
999            Masters             Yes                         No

    part_time_job  previous_grade  final_exam_score final_grade
0              No            76.9             100.0           A
1             Yes            75.5             100.0           A
2             Yes            88.5              97.3           A
3              No            85.1              83.8           B
4             Yes            61.8              68.3           D
..            ...             ...               ...         ...
995            No            60.5              70.7           C
996            No            82.2              99.5           A
997           Yes            65.2              79.2           C
998           Yes            52.2              82.2           B
999            No            45.4              70.4           C

[1000 rows x 12 columns]

In [ ]:
df.describe()

,student_id,study_time_hours,attendance_percent,sleep_hours,previous_grade,final_exam_score
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,3.570700,85.092300,6.799500,69.740900,83.543500
std,288.819436,1.478559,9.270685,1.203527,12.613425,10.341333
min,1.000000,0.500000,54.800000,3.200000,31.300000,46.800000
25%,250.750000,2.600000,78.800000,5.900000,61.000000,76.075000
50%,500.500000,3.600000,85.200000,6.800000,69.600000,83.800000
75%,750.250000,4.500000,91.900000,7.600000,78.400000,91.525000
max,1000.000000,8.100000,100.000000,10.000000,100.000000,100.000000

In [ ]:
df.fillna(0)

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
3,4,Male,2.6,77.5,8.0,0,Yes,Yes,No,85.1,83.8,B
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Male,2.8,75.4,8.2,Masters,Yes,Yes,No,60.5,70.7,C
996,997,Male,6.7,88.4,7.1,0,No,Yes,No,82.2,99.5,A
997,998,Female,2.6,84.5,8.0,High School,Yes,Yes,Yes,65.2,79.2,C
998,999,Female,4.6,85.3,8.1,High School,No,No,Yes,52.2,82.2,B
999,1000,Male,3.9,77.4,6.1,Masters,Yes,No,No,45.4,70.4,C

In [ ]:
df.head(9)

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
3,4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1,83.8,B
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D
5,6,Female,4.2,78.2,5.7,High School,Yes,No,No,79.8,81.6,B
6,7,Male,1.5,100.0,5.0,High School,Yes,Yes,Yes,58.6,69.6,D
7,8,Male,6.2,86.4,6.0,High School,Yes,Yes,No,78.4,88.0,B
8,9,Male,5.3,81.3,6.7,Bachelors,Yes,No,No,63.8,84.4,B

In [ ]:
df.tail(6)

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
994,995,Female,4.5,75.4,9.4,Bachelors,Yes,Yes,No,69.1,79.1,C
995,996,Male,2.8,75.4,8.2,Masters,Yes,Yes,No,60.5,70.7,C
996,997,Male,6.7,88.4,7.1,NaN,No,Yes,No,82.2,99.5,A
997,998,Female,2.6,84.5,8.0,High School,Yes,Yes,Yes,65.2,79.2,C
998,999,Female,4.6,85.3,8.1,High School,No,No,Yes,52.2,82.2,B
999,1000,Male,3.9,77.4,6.1,Masters,Yes,No,No,45.4,70.4,C

In [ ]:
df.fillna(method = 'ffill')

/tmp/ipykernel_3708/1145651979.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'ffill')

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
3,4,Male,2.6,77.5,8.0,Bachelors,Yes,Yes,No,85.1,83.8,B
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Male,2.8,75.4,8.2,Masters,Yes,Yes,No,60.5,70.7,C
996,997,Male,6.7,88.4,7.1,Masters,No,Yes,No,82.2,99.5,A
997,998,Female,2.6,84.5,8.0,High School,Yes,Yes,Yes,65.2,79.2,C
998,999,Female,4.6,85.3,8.1,High School,No,No,Yes,52.2,82.2,B
999,1000,Male,3.9,77.4,6.1,Masters,Yes,No,No,45.4,70.4,C

In [ ]:
df.fillna(method = 'bfill')

/tmp/ipykernel_3708/3673297803.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'bfill')

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
3,4,Male,2.6,77.5,8.0,Bachelors,Yes,Yes,No,85.1,83.8,B
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Male,2.8,75.4,8.2,Masters,Yes,Yes,No,60.5,70.7,C
996,997,Male,6.7,88.4,7.1,High School,No,Yes,No,82.2,99.5,A
997,998,Female,2.6,84.5,8.0,High School,Yes,Yes,Yes,65.2,79.2,C
998,999,Female,4.6,85.3,8.1,High School,No,No,Yes,52.2,82.2,B
999,1000,Male,3.9,77.4,6.1,Masters,Yes,No,No,45.4,70.4,C

In [ ]:
df.shape

(1000, 12)

In [ ]:
x = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [ ]:
x

array([[1, 'Male', 4.0, ..., 'No', 76.9, 100.0],
       [2, 'Female', 6.3, ..., 'Yes', 75.5, 100.0],
       [3, 'Male', 4.9, ..., 'Yes', 88.5, 97.3],
       ...,
       [998, 'Female', 2.6, ..., 'Yes', 65.2, 79.2],
       [999, 'Female', 4.6, ..., 'Yes', 52.2, 82.2],
       [1000, 'Male', 3.9, ..., 'No', 45.4, 70.4]], dtype=object)

In [ ]:
y

array(['A', 'A', 'A', 'B', 'D', 'B', 'D', 'B', 'B', 'C', 'D', 'C', 'B',
       'A', 'C', 'B', 'B', 'C', 'B', 'A', 'C', 'A', 'C', 'C', 'A', 'C',
       'C', 'A', 'B', 'B', 'B', 'B', 'A', 'A', 'A', 'A', 'B', 'B', 'B',
       'A', 'C', 'C', 'A', 'C', 'C', 'D', 'D', 'B', 'B', 'D', 'A', 'B',
       'C', 'B', 'A', 'B', 'C', 'B', 'C', 'B', 'B', 'C', 'B', 'C', 'B',
       'A', 'D', 'C', 'C', 'B', 'C', 'C', 'A', 'C', 'A', 'D', 'C', 'C',
       'C', 'B', 'A', 'C', 'D', 'A', 'A', 'D', 'C', 'A', 'C', 'B', 'C',
       'B', 'A', 'B', 'A', 'C', 'B', 'B', 'D', 'C', 'C', 'D', 'B', 'A',
       'B', 'A', 'C', 'C', 'A', 'C', 'D', 'A', 'C', 'C', 'A', 'A', 'F',
       'A', 'C', 'C', 'A', 'B', 'C', 'B', 'B', 'A', 'B', 'D', 'B', 'B',
       'A', 'C', 'C', 'B', 'B', 'A', 'F', 'B', 'B', 'B', 'B', 'C', 'B',
       'D', 'B', 'D', 'B', 'F', 'D', 'D', 'B', 'C', 'B', 'C', 'A', 'B',
       'B', 'B', 'D', 'C', 'B', 'C', 'A', 'A', 'B', 'B', 'A', 'B', 'C',
       'C', 'A', 'C', 'C', 'B', 'C', 'B', 'B', 'B', 'A', 'C', 'C', 'C',
       'C', 'B', 'B', 'A', 'B', 'B', 'A', 'D', 'B', 'A', 'C', 'B', 'A',
       'C', 'C', 'A', 'B', 'A', 'A', 'C', 'B', 'C', 'B', 'D', 'A', 'A',
       'A', 'C', 'B', 'B', 'C', 'C', 'B', 'C', 'A', 'A', 'B', 'A', 'B',
       'C', 'C', 'B', 'B', 'D', 'B', 'A', 'A', 'B', 'A', 'A', 'B', 'A',
       'B', 'B', 'A', 'B', 'A', 'B', 'B', 'B', 'D', 'A', 'C', 'A', 'A',
       'C', 'B', 'D', 'B', 'A', 'C', 'B', 'B', 'A', 'B', 'D', 'C', 'A',
       'C', 'C', 'B', 'A', 'A', 'A', 'B', 'B', 'A', 'B', 'C', 'C', 'D',
       'A', 'C', 'C', 'C', 'B', 'A', 'F', 'B', 'B', 'D', 'B', 'B', 'D',
       'D', 'D', 'C', 'C', 'A', 'A', 'B', 'A', 'A', 'B', 'C', 'B', 'D',
       'B', 'B', 'B', 'A', 'B', 'B', 'B', 'B', 'C', 'B', 'B', 'B', 'D',
       'A', 'C', 'A', 'A', 'C', 'C', 'B', 'B', 'B', 'A', 'C', 'A', 'B',
       'B', 'D', 'B', 'D', 'A', 'A', 'A', 'B', 'B', 'B', 'C', 'B', 'A',
       'C', 'B', 'A', 'A', 'A', 'C', 'A', 'C', 'B', 'D', 'A', 'C', 'C',
       'B', 'A', 'A', 'C', 'C', 'B', 'B', 'B', 'C', 'A', 'A', 'D', 'C',
       'F', 'C', 'B', 'C', 'D', 'A', 'B', 'B', 'B', 'B', 'A', 'B', 'A',
       'C', 'A', 'C', 'C', 'A', 'C', 'A', 'B', 'C', 'C', 'A', 'B', 'D',
       'B', 'B', 'C', 'A', 'D', 'C', 'C', 'B', 'A', 'C', 'B', 'A', 'B',
       'B', 'B', 'A', 'C', 'A', 'B', 'C', 'C', 'A', 'B', 'A', 'B', 'B',
       'C', 'B', 'C', 'C', 'D', 'B', 'C', 'D', 'B', 'B', 'A', 'A', 'A',
       'C', 'B', 'A', 'C', 'B', 'C', 'A', 'A', 'C', 'C', 'A', 'A', 'B',
       'B', 'B', 'B', 'C', 'C', 'B', 'A', 'D', 'C', 'B', 'A', 'B', 'B',
       'C', 'D', 'B', 'B', 'B', 'A', 'A', 'A', 'A', 'D', 'A', 'C', 'B',
       'A', 'B', 'B', 'D', 'B', 'A', 'A', 'B', 'A', 'A', 'B', 'B', 'B',
       'A', 'B', 'A', 'C', 'B', 'D', 'C', 'A', 'A', 'C', 'C', 'D', 'B',
       'B', 'C', 'C', 'B', 'D', 'A', 'C', 'A', 'A', 'B', 'A', 'A', 'C',
       'C', 'C', 'A', 'C', 'B', 'B', 'C', 'A', 'C', 'B', 'B', 'D', 'B',
       'D', 'C', 'B', 'A', 'B', 'B', 'B', 'A', 'B', 'B', 'A', 'B', 'D',
       'A', 'B', 'C', 'B', 'B', 'A', 'F', 'C', 'B', 'B', 'A', 'D', 'A',
       'C', 'B', 'A', 'B', 'C', 'A', 'C', 'B', 'D', 'B', 'B', 'C', 'A',
       'C', 'D', 'B', 'C', 'C', 'B', 'A', 'A', 'A', 'C', 'A', 'D', 'B',
       'B', 'C', 'B', 'B', 'C', 'A', 'B', 'A', 'C', 'B', 'C', 'D', 'B',
       'D', 'B', 'B', 'C', 'C', 'B', 'D', 'C', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'A', 'A', 'B', 'A', 'B', 'C', 'C', 'B', 'F', 'A', 'C',
       'C', 'C', 'C', 'A', 'A', 'B', 'C', 'A', 'B', 'A', 'C', 'B', 'C',
       'B', 'C', 'A', 'D', 'A', 'B', 'C', 'C', 'B', 'C', 'C', 'A', 'A',
       'A', 'B', 'C', 'B', 'A', 'A', 'C', 'B', 'C', 'A', 'A', 'B', 'A',
       'F', 'C', 'B', 'C', 'B', 'C', 'B', 'A', 'B', 'B', 'A', 'D', 'A',
       'A', 'B', 'A', 'A', 'A', 'A', 'D', 'D', 'A', 'B', 'C', 'B', 'D',
       'A', 'D', 'D', 'B', 'B', 'A', 'C', 'C', 'B', 'A', 'A', 'C', 'B',
       'D', 'C', 'C', 'A', 'A', 'B', 'C', 'C', 'A', 'B', 'A', 'B', 'B',
       'D', 'B', 'B', 'A', 'A', 'C', 'A', 'C', 'A', 'D', 'C', 'A', 'A',
       'F', 'A', 'B', 'A', 'C', 'B', 'C', 'D', 'A', 'B', 'A', 'A', 'B',
       'B', 'A', 'A', 'B', 'C', 'A', 'C', 'A', 'A', 'D', 'A', 'B', 'D',
       'A', 'B', 'B', 'B', 'B', 'A', 'A', 'C', 'A', 'B', 'A', 'A', 'D',
       'B', 'B', 'A', 'B', 'B', 'C', 'F', 'C', 'A', 'B', 'B', 'B', 'B',
       'C', 'B', 'A', 'B', 'A', 'A', 'B', 'C', 'B', 'C', 'A', 'B', 'B',
       'C', 'A', 'A', 'C', 'A', 'A', 'C', 'A', 'C', 'C', 'F', 'D', 'A',
       'B', 'B', 'A', 'A', 'C', 'D', 'A', 'B', 'A', 'A', 'A', 'B', 'B',
       'B', 'F', 'C', 'B', 'B', 'B', 'A', 'C', 'C', 'B', 'B', 'B', 'C',
       'A', 'D', 'C', 'C', 'A', 'A', 'B', 'B', 'C', 'C', 'A', 'C', 'A',
       'C', 'B', 'B', 'B', 'A', 'B', 'B', 'B', 'B', 'C', 'B', 'B', 'B',
       'B', 'D', 'A', 'B', 'A', 'A', 'B', 'B', 'A', 'B', 'C', 'A', 'C',
       'B', 'D', 'A', 'C', 'B', 'C', 'B', 'B', 'B', 'A', 'A', 'B', 'A',
       'A', 'C', 'B', 'A', 'B', 'A', 'D', 'C', 'B', 'B', 'B', 'C', 'A',
       'A', 'C', 'C', 'C', 'B', 'C', 'A', 'B', 'C', 'C', 'C', 'B', 'A',
       'C', 'D', 'D', 'D', 'B', 'C', 'D', 'A', 'A', 'B', 'B', 'C', 'B',
       'A', 'A', 'B', 'B', 'C', 'B', 'B', 'B', 'A', 'B', 'C', 'A', 'B',
       'A', 'C', 'A', 'A', 'A', 'C', 'B', 'C', 'D', 'C', 'C', 'A', 'B',
       'B', 'A', 'C', 'C', 'C', 'B', 'D', 'A', 'A', 'A', 'C', 'B', 'A',
       'D', 'C', 'B', 'B', 'C', 'A', 'B', 'A', 'B', 'B', 'B', 'C', 'B',
       'C', 'C', 'D', 'C', 'A', 'A', 'D', 'C', 'A', 'C', 'B', 'C', 'D',
       'D', 'B', 'C', 'B', 'A', 'A', 'C', 'C', 'B', 'C', 'A', 'B', 'B',
       'B', 'A', 'B', 'B', 'C', 'A', 'C', 'C', 'A', 'C', 'B', 'C'],
      dtype=object)

In [ ]:
x_train

array([[688, 'Male', 1.6, ..., 'No', 88.7, 74.4],
       [501, 'Male', 4.4, ..., 'No', 53.6, 76.1],
       [333, 'Female', 3.0, ..., 'Yes', 93.2, 82.8],
       ...,
       [630, 'Male', 3.8, ..., 'No', 65.2, 81.3],
       [560, 'Female', 1.9, ..., 'Yes', 80.4, 73.5],
       [685, 'Male', 3.4, ..., 'No', 70.2, 83.8]], dtype=object)

In [ ]:
y_train

array(['C', 'C', 'B', 'A', 'B', 'A', 'C', 'B', 'D', 'C', 'C', 'C', 'B',
       'C', 'B', 'C', 'D', 'A', 'C', 'D', 'B', 'C', 'D', 'B', 'C', 'A',
       'B', 'B', 'B', 'B', 'A', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'C', 'C', 'C', 'A', 'F', 'B', 'A', 'B', 'A', 'B', 'C', 'B', 'A',
       'D', 'C', 'D', 'C', 'B', 'A', 'C', 'B', 'A', 'A', 'A', 'B', 'C',
       'B', 'B', 'D', 'A', 'C', 'D', 'C', 'A', 'A', 'B', 'A', 'A', 'B',
       'B', 'C', 'A', 'A', 'A', 'C', 'B', 'A', 'B', 'B', 'B', 'C', 'A',
       'B', 'A', 'C', 'B', 'B', 'B', 'C', 'C', 'D', 'A', 'C', 'B', 'C',
       'C', 'C', 'C', 'A', 'B', 'B', 'C', 'C', 'B', 'C', 'A', 'C', 'D',
       'D', 'C', 'D', 'C', 'C', 'B', 'F', 'A', 'C', 'B', 'B', 'A', 'C',
       'C', 'C', 'B', 'D', 'C', 'A', 'B', 'F', 'C', 'A', 'B', 'A', 'C',
       'B', 'B', 'A', 'D', 'D', 'B', 'A', 'B', 'B', 'B', 'B', 'B', 'A',
       'B', 'D', 'B', 'C', 'C', 'C', 'B', 'B', 'C', 'A', 'C', 'C', 'C',
       'D', 'B', 'A', 'B', 'A', 'B', 'B', 'B', 'D', 'B', 'C', 'C', 'B',
       'B', 'B', 'A', 'B', 'C', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A',
       'C', 'C', 'B', 'B', 'A', 'A', 'C', 'D', 'C', 'C', 'A', 'A', 'B',
       'B', 'C', 'C', 'B', 'A', 'A', 'C', 'B', 'C', 'B', 'A', 'A', 'A',
       'A', 'A', 'A', 'B', 'A', 'C', 'B', 'C', 'B', 'B', 'A', 'D', 'C',
       'B', 'B', 'A', 'C', 'C', 'A', 'A', 'A', 'C', 'B', 'C', 'A', 'D',
       'B', 'B', 'D', 'D', 'C', 'B', 'B', 'B', 'B', 'B', 'A', 'B', 'B',
       'C', 'B', 'B', 'A', 'D', 'D', 'C', 'A', 'B', 'C', 'B', 'C', 'B',
       'B', 'B', 'A', 'A', 'A', 'B', 'C', 'C', 'B', 'A', 'C', 'A', 'C',
       'A', 'B', 'D', 'A', 'C', 'A', 'A', 'C', 'D', 'A', 'B', 'A', 'B',
       'B', 'C', 'A', 'C', 'B', 'A', 'B', 'A', 'A', 'B', 'B', 'C', 'A',
       'B', 'A', 'A', 'A', 'B', 'A', 'B', 'A', 'A', 'A', 'B', 'A', 'A',
       'C', 'A', 'A', 'B', 'C', 'A', 'C', 'B', 'B', 'B', 'B', 'B', 'C',
       'A', 'A', 'A', 'B', 'B', 'B', 'C', 'A', 'C', 'A', 'B', 'B', 'A',
       'B', 'B', 'C', 'D', 'B', 'A', 'B', 'C', 'D', 'D', 'A', 'A', 'B',
       'C', 'A', 'B', 'B', 'C', 'C', 'A', 'B', 'C', 'B', 'D', 'B', 'A',
       'B', 'C', 'B', 'B', 'A', 'A', 'A', 'B', 'A', 'A', 'A', 'C', 'A',
       'B', 'C', 'C', 'C', 'B', 'C', 'B', 'B', 'A', 'A', 'C', 'D', 'A',
       'D', 'A', 'D', 'B', 'B', 'A', 'D', 'A', 'B', 'B', 'C', 'C', 'C',
       'A', 'D', 'B', 'C', 'C', 'B', 'A', 'A', 'D', 'B', 'D', 'A', 'A',
       'D', 'C', 'A', 'C', 'C', 'B', 'B', 'C', 'B', 'C', 'B', 'D', 'C',
       'B', 'B', 'A', 'B', 'A', 'B', 'C', 'A', 'C', 'C', 'B', 'B', 'B',
       'C', 'C', 'F', 'B', 'C', 'A', 'A', 'B', 'B', 'B', 'C', 'B', 'B',
       'A', 'C', 'C', 'A', 'B', 'D', 'D', 'A', 'B', 'B', 'B', 'A', 'B',
       'C', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'F', 'C', 'B', 'B', 'B',
       'A', 'A', 'A', 'C', 'C', 'B', 'C', 'B', 'A', 'C', 'B', 'B', 'B',
       'C', 'D', 'A', 'B', 'A', 'C', 'A', 'D', 'F', 'C', 'B', 'B', 'B',
       'A', 'B', 'A', 'B', 'C', 'A', 'C', 'C', 'A', 'C', 'C', 'A', 'C',
       'A', 'D', 'A', 'B', 'C', 'A', 'B', 'A', 'B', 'B', 'B', 'B', 'A',
       'A', 'F', 'C', 'C', 'A', 'A', 'B', 'B', 'B', 'C', 'B', 'B', 'B',
       'B', 'B', 'C', 'B', 'A', 'B', 'A', 'B', 'C', 'A', 'A', 'A', 'A',
       'B', 'C', 'A', 'A', 'A', 'C', 'C', 'C', 'D', 'D', 'B', 'A', 'B',
       'D', 'B', 'D', 'B', 'C', 'C', 'A', 'C', 'B', 'C', 'A', 'D', 'C',
       'D', 'D', 'B', 'B', 'C', 'C', 'A', 'B', 'B', 'A', 'C', 'B', 'A',
       'C', 'B', 'C', 'C', 'B', 'A', 'D', 'C', 'B', 'B', 'A', 'C', 'C',
       'A', 'B', 'D', 'C', 'C', 'B', 'B', 'B', 'C', 'B', 'C', 'B', 'B',
       'C', 'A', 'A', 'C', 'B', 'C', 'C', 'C', 'B', 'B', 'A', 'C', 'C',
       'A', 'A', 'C', 'C', 'D', 'B', 'B', 'B', 'C', 'B', 'D', 'C', 'A',
       'A', 'C', 'B', 'B', 'B', 'B', 'A', 'C', 'D', 'D', 'C', 'A', 'C',
       'B', 'B', 'C', 'B', 'C', 'A', 'C', 'C', 'A', 'C', 'B', 'B', 'D',
       'A', 'B', 'C', 'D', 'A', 'A', 'D', 'D', 'C', 'A', 'C', 'D', 'B',
       'C', 'B', 'C', 'A', 'C', 'A', 'C', 'A', 'A', 'B', 'D', 'B', 'B',
       'C', 'A', 'A', 'B', 'A', 'D', 'B', 'B', 'B', 'A', 'C', 'B', 'C',
       'A', 'A', 'A', 'C', 'B', 'B', 'C', 'B', 'B', 'A', 'B', 'B', 'C',
       'B', 'C', 'D', 'C', 'C', 'A', 'A', 'D', 'C', 'A', 'A', 'C', 'D',
       'A', 'F', 'B', 'C', 'A', 'B', 'C', 'A', 'A', 'A', 'A', 'C', 'B',
       'A', 'B', 'A', 'A', 'B', 'B', 'D', 'A', 'B', 'C', 'A', 'A', 'D',
       'A', 'A', 'C', 'A', 'B', 'C', 'B', 'B', 'B', 'B', 'A', 'C', 'C',
       'C', 'B', 'B', 'C', 'B', 'C', 'B'], dtype=object)

In [ ]:
x_test

array([[994, 'Female', 6.2, ..., 'No', 75.4, 92.7],
       [860, 'Male', 1.7, ..., 'Yes', 80.0, 66.5],
       [299, 'Male', 1.7, ..., 'No', 67.9, 69.2],
       ...,
       [216, 'Male', 2.1, ..., 'No', 58.9, 74.7],
       [654, 'Male', 5.1, ..., 'Yes', 58.8, 74.8],
       [151, 'Male', 2.2, ..., 'No', 66.2, 84.7]], dtype=object)

In [ ]:
y_test

array(['A', 'D', 'D', 'B', 'B', 'C', 'A', 'A', 'B', 'A', 'C', 'A', 'A',
       'B', 'B', 'B', 'B', 'B', 'C', 'C', 'B', 'A', 'B', 'D', 'A', 'C',
       'D', 'A', 'F', 'A', 'A', 'A', 'A', 'F', 'B', 'A', 'B', 'B', 'A',
       'B', 'A', 'A', 'A', 'B', 'A', 'C', 'A', 'C', 'C', 'B', 'A', 'B',
       'B', 'C', 'B', 'C', 'D', 'C', 'B', 'B', 'A', 'C', 'B', 'B', 'A',
       'C', 'A', 'B', 'C', 'C', 'A', 'B', 'D', 'C', 'A', 'B', 'D', 'A',
       'A', 'B', 'C', 'D', 'C', 'C', 'B', 'A', 'A', 'A', 'B', 'A', 'A',
       'B', 'A', 'F', 'B', 'B', 'C', 'A', 'C', 'B', 'A', 'B', 'A', 'C',
       'C', 'A', 'A', 'C', 'B', 'B', 'B', 'D', 'C', 'A', 'A', 'C', 'A',
       'C', 'A', 'C', 'C', 'A', 'C', 'C', 'B', 'B', 'B', 'B', 'C', 'F',
       'C', 'C', 'B', 'A', 'D', 'B', 'A', 'B', 'B', 'A', 'D', 'A', 'D',
       'D', 'A', 'B', 'B', 'C', 'A', 'A', 'C', 'B', 'B', 'B', 'D', 'B',
       'B', 'D', 'A', 'A', 'C', 'B', 'B', 'B', 'A', 'A', 'B', 'D', 'B',
       'C', 'A', 'A', 'D', 'B', 'D', 'A', 'B', 'B', 'C', 'B', 'C', 'C',
       'B', 'A', 'A', 'B', 'B', 'B', 'B', 'B', 'B', 'C', 'A', 'B', 'A',
       'B', 'D', 'C', 'C', 'B'], dtype=object)